
try { demo.core.init(); } catch (e) { console.error("An error occurred when calling (demo.core/init)"); console.error(e); }